# The Docker Config version. Do not change.
version: "3"
services:
  mysqldb:
    image: mysql:8
    container_name: jokeservicedb
    volumes:
      - jokeappdata:/var/lib/mysql
    networks:
      - jokeappnetwork
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_db
      # Create user; requires a new volume. Will not create on existing volumes.
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    ports:
    # Map local port 3307 to container port 3306 to prevent conflict with local MySQL
      - "3307:3306"
  api:
    image: alundin/jokeservice:latest
    container_name: jokeservice
    environment:
      DB_USER: user1
      DB_PASSWORD: password
    depends_on:
      - mysqldb
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - jokeappnetwork
# Persists data across deployments so data isn't lost
volumes:
  jokeappdata:
    driver: local
# Defines a shared network for all services to connect them and share data
networks:
  jokeappnetwork: